version: "3"
services:
  # nginx_1:
  #   image: ghcr.io/linuxserver/nginx
  #   container_name: AppliDB-react
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Manila
  #   volumes:
  #     - ./site/build:/config/www
  #   ports:
  #     - 3080:80
  #     - 3443:443
  #   depends_on:
  #     - strapi
  #   restart: unless-stopped

  # nginx_2:
  #   image: ghcr.io/linuxserver/nginx
  #   container_name: JODB-react
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Manila
  #   volumes:
  #     - /home/greg/Documents/jo-db/build:/config/www
  #   ports:
  #     - 3081:80
  #     - 3444:443
  #   depends_on:
  #     - strapi
  #   restart: unless-stopped

  strapi:
    image: strapi/strapi
    container_name: AppliDB-strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./strapi:/srv/app
    ports:
      - 1337:1337
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: AppliDB-mongo
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - ./data:/data/db
    restart: unless-stopped
