version: "3"
services:
  # reactjs:
  #   image: nginx
  #   volumes: # BUILD REACTJS FIRST, YOU PEPEGA
  #     - "./site/build:/usr/share/nginx/html"
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - strapi
  nginx:
    image: ghcr.io/linuxserver/nginx
    container_name: static_react
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ./site/build:/config/www
    ports:
      - 3080:80
      - 3443:443
    depends_on:
      - strapi
    restart: unless-stopped

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./strapi:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - ./data:/data/db
